### ISSUE TITLE
Testing in Windows sandbox

### ISSUE THREAD

**Issue by sapols** [sapols/pyhc-environment-files#1]
@xandrd Remember to do this 👍

**Comment by xandrd** [comment]
`ERROR: Failed building wheel for aacgmv2`

Require "Microsoft C++ Build Tools" installed.
https://visualstudio.microsoft.com/visual-cpp-build-tools/

With MS installer, "Desktop development with C++" must be selected, which are not selected by default.

**Comment by xandrd** [comment]
All other packages from [pyhc-requirements.txt](https://github.com/sapols/pyhc-environment-files/blob/main/pyhc-requirements.txt) were installed without further problems.

**Comment by xandrd** [comment]
Failed to install `apexpy` package.

`..\..\meson.build:1:0: ERROR: Compiler cl can not compile programs.`

**Comment by xandrd** [comment]
`apexpy` (and other packages) requires `gfortran` to be installed (I believe with toolchain). `apexpy` uses `menson` which fails during compiler sanity check when `cl` is called with an option `/Wno-unused-function`. `cl` does not have this option but a `gcc` does. 

Note, `apexpy` documentation explicitly said that "you MUST have a fortran compiler installed on your system". So, the easies way to install it on Windows is to download MSYS2 https://www.msys2.org/, and install `pacman -S base-devel mingw-w64-x86_64-toolchain`. After that include bin folder (e.g., `c:\msys64\mingw64\bin\`) to windows PATH.

**Comment by xandrd** [comment]
Failed to install `pyflct` package.

` pyflct\../cextern/flctsubs.h(45): fatal error C1083: Cannot open include file: 'fftw3.h': No such file or directory`

**Comment by xandrd** [comment]
`pyflct` package depends on `FFTW` http://www.fftw.org/. The developers of `pyflct` support windows installation only via Anaconda. 
EDIT: I was wrong, package - `pyfftw` is not a `pyflct`, but a requirement.

`pyfftw` can be installed with precompiled DLL files for FFTW. The developers of `pyflct` provide [very clear instuctions](https://pyflct.readthedocs.io/en/latest/install.html). In short, *.lib files of FFTW must be created with  VS developer console:
```
lib /def:libfftw3-3.def
lib /def:libfftw3f-3.def
lib /def:libfftw3l-3.def
```
The FFTW files must be added to the PATH. While installing the package the libraries folder must be visible for the compiler. This can be done by setting INCLUDE environmental variable, e.g.:
```
set INCLUDE=%INCLUDE%;C:\fftw64
```

**Comment by xandrd** [comment]
Running [import-test.py](https://github.com/sapols/pyhc-environment-files/blob/main/import-test.py) 
- fails importing `aidapy`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\aidapy\__init__.py", line 4, in <module>
    from aidapy.aidafunc.load_data import load_data
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\aidapy\aidafunc\load_data.py", line 14, in <module>
    from aidapy.data.mission.mission import Mission
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\aidapy\data\mission\mission.py", line 8, in <module>
    import aidapy.data.mission.omni as omni
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\aidapy\data\mission\omni.py", line 12, in <module>
    import heliopy.data.omni as omni
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\heliopy\data\__init__.py", line 3, in <module>
    raise_import_error()
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\heliopy\__init__.py", line 10, in raise_import_error
    raise ImportError(
ImportError: HelioPy is no longer maintained or supported.
Most functionality is now available elsewhere.
See https://github.com/heliopython/heliopy/blob/main/README.md for more info.

Downgrade to heliopy<1 to continue using the legacy code.
```

- fails importing ` hissw`:
```
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\import-test.py", line 15, in <module>
    import hissw
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\hissw\__init__.py", line 4, in <module>
    from .read_config import defaults
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\hissw\read_config.py", line 10, in <module>
    defaults['hissw_home'] = os.path.join(os.environ['HOME'], '.hissw')
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
```

- fails importing `import ocbpy`:
```
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\import-test.py", line 23, in <module>
    import ocbpy
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\ocbpy\__init__.py", line 16, in <module>
    from ocbpy import _boundary
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\ocbpy\_boundary.py", line 30, in <module>
    from ocbpy.boundaries.files import get_default_file
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\ocbpy\boundaries\__init__.py", line 11, in <module>
    from ocbpy.boundaries import dmsp_ssj_files
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\ocbpy\boundaries\dmsp_ssj_files.py", line 33, in <module>
    from spacepy import pycdf
  File "C:\Users\WDAGUtilityAccount\Documents\pyhc-environment-files\pyhc-env\lib\site-packages\spacepy\pycdf\__init__.py", line 1301, in <module>
    raise Exception(('Cannot load CDF C library; checked {0}. '
Exception: Cannot load CDF C library; checked . Try 'os.environ["CDF_LIB"] = library_directory' before import.
```

**Comment by xandrd** [comment]
Solution for `aidapy` is to downgrade heliopy:

`pip install heliopy==0.15.4`

**Comment by xandrd** [comment]
Solution for `hissw` is to setup environmental variable "HOME";

![image](https://github.com/sapols/pyhc-environment-files/assets/13282744/8e3e6ab5-f844-4465-aa01-29386a326832)

**Comment by xandrd** [comment]
Problem with `ocbpy` occur during `import spacepy.pycdf`.
pycdf (python interface to CDF files), requires CDF software. v.3.9 can be installed: https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/latest/windows/cdf3.9.0_64bit_MS_Installer.msi

In the CDF installation folder, scripts `setenv.bat` and `setenv.ps1` can be found. One of those scripts can be executed to setup environmental variables BEFORE running python. Alternatively, setenv.bat can be modified invoking `setx` to set variables permanently for the selected user. However, it requires changing syntax  to `setx VAR_NAME "VALUE"`

**Comment by xandrd** [comment]
I have trouble with installing `apexpy` again:
```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\WDAGUtilityAccount\\AppData\\Local\\Temp\\pip-build-env-i0tx7mb4\\overlay\\Lib\\site-packages\\jupyterlab_flake8\\labextension\\static\\vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_cssW-926fd9.774fd78a1e21916fe4de.js.map'
```
